[project]
name = "tom-bluff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.0.0",
    "numpy>=2.1.3",
    "pettingzoo>=1.24.3",
    "typing>=3.10.0.0",
]
